/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package posttest1;

/**
 *
 * @author USER
 */
public class Modul2 extends javax.swing.JFrame {
 int pil;
 float hsl;
    /**
     * Creates new form Hitungan
     */
    public Modul2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblnilaix = new javax.swing.JLabel();
        lblnilaiy = new javax.swing.JLabel();
        rbtambah = new javax.swing.JRadioButton();
        rbkurang = new javax.swing.JRadioButton();
        rbkali = new javax.swing.JRadioButton();
        rbbagi = new javax.swing.JRadioButton();
        tfnilaix = new javax.swing.JTextField();
        tfnilaiy = new javax.swing.JTextField();
        tfhasil = new javax.swing.JTextField();
        lblhasil = new javax.swing.JLabel();
        btnhitung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblnilaix.setText("Nilai X");

        lblnilaiy.setText("Nilai Y");

        bg.add(rbtambah);
        rbtambah.setText("Tambah");
        rbtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtambahActionPerformed(evt);
            }
        });

        bg.add(rbkurang);
        rbkurang.setText("Kurang");
        rbkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbkurangActionPerformed(evt);
            }
        });

        bg.add(rbkali);
        rbkali.setText("Kali");
        rbkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbkaliActionPerformed(evt);
            }
        });

        bg.add(rbbagi);
        rbbagi.setText("Bagi");
        rbbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbbagiActionPerformed(evt);
            }
        });

        lblhasil.setText("Hasil");

        btnhitung.setText("Hitung");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblhasil)
                        .addGap(28, 28, 28)
                        .addComponent(tfhasil, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblnilaix)
                                .addGap(29, 29, 29)
                                .addComponent(tfnilaix))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblnilaiy)
                                .addGap(29, 29, 29)
                                .addComponent(tfnilaiy, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(rbtambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbkurang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbkali)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbbagi))
                            .addComponent(btnhitung))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnilaix)
                    .addComponent(tfnilaix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnilaiy)
                    .addComponent(tfnilaiy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbkurang, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtambah)
                    .addComponent(rbkali)
                    .addComponent(rbbagi))
                .addGap(13, 13, 13)
                .addComponent(btnhitung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfhasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblhasil))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        // TODO add your handling code here:
        switch (pil) {
           case 1: hsl = Float.parseFloat(tfnilaix.getText()) + Float.parseFloat(tfnilaiy.getText());   
                   tfhasil.setText(Float.toString(hsl));break; 
               
           case 2: hsl = Float.parseFloat(tfnilaix.getText()) - Float.parseFloat(tfnilaiy.getText()); 
                   tfhasil.setText(Float.toString(hsl));break;
               
           case 3: hsl = Float.parseFloat(tfnilaix.getText()) * Float.parseFloat(tfnilaiy.getText());
                   tfhasil.setText(Float.toString(hsl));break; 
               
           case 4: hsl = Float.parseFloat(tfnilaix.getText()) / Float.parseFloat(tfnilaiy.getText());
                   tfhasil.setText(Float.toString(hsl));break; 
       } 
    }//GEN-LAST:event_btnhitungActionPerformed

    private void rbtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtambahActionPerformed
        // TODO add your handling code here:
        pil = 1;
    }//GEN-LAST:event_rbtambahActionPerformed

    private void rbkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbkurangActionPerformed
        // TODO add your handling code here:
        pil = 2;
    }//GEN-LAST:event_rbkurangActionPerformed

    private void rbbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbbagiActionPerformed
        // TODO add your handling code here:
        pil = 4;
    }//GEN-LAST:event_rbbagiActionPerformed

    private void rbkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbkaliActionPerformed
        // TODO add your handling code here:
        pil = 3;
    }//GEN-LAST:event_rbkaliActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        tfnilaix.setText("");
        tfnilaiy.setText("");
        tfhasil.setText("");
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modul2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modul2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modul2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modul2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modul2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg;
    private javax.swing.JButton btnhitung;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblhasil;
    private javax.swing.JLabel lblnilaix;
    private javax.swing.JLabel lblnilaiy;
    private javax.swing.JRadioButton rbbagi;
    private javax.swing.JRadioButton rbkali;
    private javax.swing.JRadioButton rbkurang;
    private javax.swing.JRadioButton rbtambah;
    private javax.swing.JTextField tfhasil;
    private javax.swing.JTextField tfnilaix;
    private javax.swing.JTextField tfnilaiy;
    // End of variables declaration//GEN-END:variables
}
