/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package posttest2;

/**
 *
 * @author USER
 */
public class Nilai_Tambahan_Modul3 extends javax.swing.JFrame {

    /**
     * Creates new form Nilai_Tambahan_Modul3
     */
    public Nilai_Tambahan_Modul3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgjk = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblfp = new javax.swing.JLabel();
        lblsmk = new javax.swing.JLabel();
        lblnamal = new javax.swing.JLabel();
        lblnamap = new javax.swing.JLabel();
        lblttl = new javax.swing.JLabel();
        lblalamat = new javax.swing.JLabel();
        lblstatus = new javax.swing.JLabel();
        lblpk = new javax.swing.JLabel();
        lbljk = new javax.swing.JLabel();
        cbstatus = new javax.swing.JComboBox();
        rbl = new javax.swing.JRadioButton();
        rbp = new javax.swing.JRadioButton();
        cbpk = new javax.swing.JCheckBox();
        lbljadwal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jljadwal = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        tao = new javax.swing.JTextArea();
        tfnl = new javax.swing.JTextField();
        tfnp = new javax.swing.JTextField();
        tfttl = new javax.swing.JTextField();
        tfalamat = new javax.swing.JTextField();
        btntampil = new javax.swing.JButton();
        cbpk2 = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        tao2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 1, true));

        lblfp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblfp.setText("FORMULIR PENDAFTARAN");

        lblsmk.setText("\"SEKOLAH MUSIK KASIH\"");

        lblnamal.setText("Nama Lengkap");

        lblnamap.setText("Nama Panggilan");

        lblttl.setText("Tempat, Tanggal Lahir");

        lblalamat.setText("Alamat");

        lblstatus.setText("Status");

        lblpk.setText("Pilihan Kursus");

        lbljk.setText("Jenis Kelamin");

        cbstatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pelajar", "Mahasiswa", "Pegawai Negeri", "Karyawan Swasta", "Lain-Lain" }));

        bgjk.add(rbl);
        rbl.setText("Laki-Laki");

        bgjk.add(rbp);
        rbp.setText("Perempuan");

        cbpk.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbpkStateChanged(evt);
            }
        });
        cbpk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbpkActionPerformed(evt);
            }
        });

        lbljadwal.setText("Jadwal Kursus");

        jljadwal.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Senin,Selasa,Rabu (13.00, 14.00, 15.00, 16.00)", "Rabu,Kamis,Jumat (14.00, 15.00, 16.00, 17.00)", "Senin & Rabu (10.00, 11.00)", "Selasa & Kamis (10.00, 11.00)", "Jumat (08.00, 09.00, 10.00)", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jljadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jljadwalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jljadwal);

        tao.setColumns(20);
        tao.setRows(5);
        jScrollPane2.setViewportView(tao);

        btntampil.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btntampil.setText("TAMPIL");
        btntampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntampilActionPerformed(evt);
            }
        });

        cbpk2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbpk2StateChanged(evt);
            }
        });

        tao2.setColumns(20);
        tao2.setRows(5);
        jScrollPane3.setViewportView(tao2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblstatus)
                                        .addComponent(lblalamat))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(lblpk)))
                                .addGap(86, 86, 86)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfalamat)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(cbpk, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(cbpk2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbljadwal)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btntampil)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblnamal)
                                        .addComponent(lblnamap)
                                        .addComponent(lblttl)
                                        .addComponent(lbljk)))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfnl)
                                    .addComponent(tfnp)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(rbl)
                                                .addGap(48, 48, 48)
                                                .addComponent(rbp))
                                            .addComponent(lblsmk))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(tfttl)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(lblfp)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblfp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblsmk)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblnamal)
                            .addComponent(tfnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblnamap)
                            .addComponent(tfnp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbl)
                            .addComponent(rbp)
                            .addComponent(lbljk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblttl)
                            .addComponent(tfttl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblalamat)
                            .addComponent(tfalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblstatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblpk)
                                .addGap(7, 7, 7))
                            .addComponent(cbpk2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(cbpk))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbljadwal)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btntampil)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbpkStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbpkStateChanged
        // TODO add your handling code here:
        if (cbpk.isSelected()){
            cbpk.setText("Gitar");
        }  else {
            cbpk.setText("Basis");
        }
    }//GEN-LAST:event_cbpkStateChanged

    private void cbpk2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbpk2StateChanged
        // TODO add your handling code here:
        if (cbpk2.isSelected()){
            cbpk2.setText("Piano");
        }  else {
            cbpk2.setText("Keyboard");
        }
    }//GEN-LAST:event_cbpk2StateChanged

    private void btntampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntampilActionPerformed
        // TODO add your handling code here:
        String JenisKelamin=null;
        if(rbl.isSelected())
            JenisKelamin = rbl.getText();
        else if(rbp.isSelected())
            JenisKelamin = rbp.getText();
        
        String namal = tfnl.getText();
        String namap = tfnp.getText();
        String ttl = tfttl.getText();
        String alamat = tfalamat.getText();
        String status = cbstatus.getSelectedItem().toString();
        
        tao.setText (" Nama Lengkap     : "+namal
                +"\n Nama Panggilan   : "+namap
                +"\n JenisKelamin    : "+JenisKelamin
                +"\n TTL   : "+ttl
                 +"\n Alamat   : "+alamat
                 +"\n Status    : "+status);
        
    }//GEN-LAST:event_btntampilActionPerformed

    private void jljadwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jljadwalMouseClicked
        // TODO add your handling code here:
        tao2.append(jljadwal.getSelectedValue()+", ");
    }//GEN-LAST:event_jljadwalMouseClicked

    private void cbpkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbpkActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cbpkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nilai_Tambahan_Modul3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nilai_Tambahan_Modul3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nilai_Tambahan_Modul3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nilai_Tambahan_Modul3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nilai_Tambahan_Modul3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgjk;
    private javax.swing.JButton btntampil;
    private javax.swing.JCheckBox cbpk;
    private javax.swing.JCheckBox cbpk2;
    private javax.swing.JComboBox cbstatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList jljadwal;
    private javax.swing.JLabel lblalamat;
    private javax.swing.JLabel lblfp;
    private javax.swing.JLabel lbljadwal;
    private javax.swing.JLabel lbljk;
    private javax.swing.JLabel lblnamal;
    private javax.swing.JLabel lblnamap;
    private javax.swing.JLabel lblpk;
    private javax.swing.JLabel lblsmk;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JLabel lblttl;
    private javax.swing.JRadioButton rbl;
    private javax.swing.JRadioButton rbp;
    private javax.swing.JTextArea tao;
    private javax.swing.JTextArea tao2;
    private javax.swing.JTextField tfalamat;
    private javax.swing.JTextField tfnl;
    private javax.swing.JTextField tfnp;
    private javax.swing.JTextField tfttl;
    // End of variables declaration//GEN-END:variables
}
