/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package posttest3;

/**
 *
 * @author USER
 */
public class sispk extends javax.swing.JFrame {

    /**
     * Creates new form sismk
     */
    public sispk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnltengah = new javax.swing.JPanel();
        lblstart = new javax.swing.JLabel();
        lblkiri = new javax.swing.JPanel();
        lblgallery = new javax.swing.JLabel();
        lbllogin = new javax.swing.JLabel();
        lblhistory = new javax.swing.JLabel();
        pnlatas = new javax.swing.JPanel();
        lblunmul = new javax.swing.JLabel();
        lblfkti = new javax.swing.JLabel();
        lblspk = new javax.swing.JLabel();
        lblpps = new javax.swing.JLabel();
        lblfikti = new javax.swing.JLabel();
        lblum = new javax.swing.JLabel();
        pnlmenu = new javax.swing.JPanel();
        btnhome = new javax.swing.JButton();
        btnabout = new javax.swing.JButton();
        btncu = new javax.swing.JButton();
        pnlkanan = new javax.swing.JPanel();
        lblpenilaian = new javax.swing.JLabel();
        lblpengunjung = new javax.swing.JLabel();
        pnlbawah = new javax.swing.JPanel();
        lblcopy = new javax.swing.JLabel();
        pnlhome = new javax.swing.JPanel();
        lblhh = new javax.swing.JLabel();
        pnlabout = new javax.swing.JPanel();
        lblha = new javax.swing.JLabel();
        pnlcu = new javax.swing.JPanel();
        lblhcu = new javax.swing.JLabel();
        menuutama = new javax.swing.JMenuBar();
        submenuutama = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        submenuedit = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        menukeluar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnltengah.setBackground(new java.awt.Color(204, 204, 255));

        lblstart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posttest3/gambar/start.jpg"))); // NOI18N

        lblkiri.setBackground(new java.awt.Color(0, 0, 102));

        lblgallery.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        lblgallery.setForeground(new java.awt.Color(255, 255, 255));
        lblgallery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posttest3/gambar/galery.jpg"))); // NOI18N
        lblgallery.setText("GALLERY");

        lbllogin.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        lbllogin.setForeground(new java.awt.Color(255, 255, 255));
        lbllogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posttest3/gambar/login.jpg"))); // NOI18N
        lbllogin.setText("LOGIN");

        lblhistory.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        lblhistory.setForeground(new java.awt.Color(255, 255, 255));
        lblhistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posttest3/gambar/history.jpg"))); // NOI18N
        lblhistory.setText("HISTORY");

        javax.swing.GroupLayout lblkiriLayout = new javax.swing.GroupLayout(lblkiri);
        lblkiri.setLayout(lblkiriLayout);
        lblkiriLayout.setHorizontalGroup(
            lblkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblkiriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lblkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbllogin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblgallery)
                    .addComponent(lblhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        lblkiriLayout.setVerticalGroup(
            lblkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblkiriLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbllogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblgallery)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        pnlatas.setBackground(new java.awt.Color(102, 102, 255));

        lblunmul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posttest3/gambar/um.jpg"))); // NOI18N
        lblunmul.setPreferredSize(new java.awt.Dimension(262, 225));

        lblfkti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posttest3/gambar/fkti.jpg"))); // NOI18N

        lblspk.setFont(new java.awt.Font("OCR-B 10 BT", 1, 14)); // NOI18N
        lblspk.setForeground(new java.awt.Color(255, 204, 0));
        lblspk.setText("SISTEM PENDUKUNG KEPUTUSAN");

        lblpps.setFont(new java.awt.Font("OCR-B 10 BT", 1, 14)); // NOI18N
        lblpps.setForeground(new java.awt.Color(255, 204, 0));
        lblpps.setText("PEMILIHAN PROGRAM STUDI ");

        lblfikti.setFont(new java.awt.Font("OCR-B 10 BT", 1, 14)); // NOI18N
        lblfikti.setForeground(new java.awt.Color(255, 204, 0));
        lblfikti.setText("FAKULTAS ILMU KOMPUTER & TEKNOLOGI INFORMASI");

        lblum.setFont(new java.awt.Font("OCR-B 10 BT", 1, 14)); // NOI18N
        lblum.setForeground(new java.awt.Color(255, 204, 0));
        lblum.setText("UNIVERSITAS MULAWARMAN");

        pnlmenu.setLayout(new java.awt.GridLayout(1, 0, 15, 0));

        btnhome.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        btnhome.setText("Home");
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });
        pnlmenu.add(btnhome);

        btnabout.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        btnabout.setText("About");
        btnabout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaboutActionPerformed(evt);
            }
        });
        pnlmenu.add(btnabout);

        btncu.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        btncu.setText("Contact Us");
        btncu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncuActionPerformed(evt);
            }
        });
        pnlmenu.add(btncu);

        javax.swing.GroupLayout pnlatasLayout = new javax.swing.GroupLayout(pnlatas);
        pnlatas.setLayout(pnlatasLayout);
        pnlatasLayout.setHorizontalGroup(
            pnlatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlatasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblunmul, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlatasLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(pnlmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlatasLayout.createSequentialGroup()
                        .addGroup(pnlatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlatasLayout.createSequentialGroup()
                                .addGap(222, 222, 222)
                                .addComponent(lblum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlatasLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlatasLayout.createSequentialGroup()
                                        .addComponent(lblfikti)
                                        .addGap(120, 120, 120))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlatasLayout.createSequentialGroup()
                                        .addComponent(lblpps)
                                        .addGap(208, 208, 208))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlatasLayout.createSequentialGroup()
                                        .addComponent(lblspk)
                                        .addGap(200, 200, 200)))))
                        .addComponent(lblfkti)
                        .addGap(111, 111, 111))))
        );
        pnlatasLayout.setVerticalGroup(
            pnlatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlatasLayout.createSequentialGroup()
                .addGroup(pnlatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlatasLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblspk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblpps)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblfikti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblum)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlatasLayout.createSequentialGroup()
                        .addContainerGap(23, Short.MAX_VALUE)
                        .addGroup(pnlatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblfkti, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblunmul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(pnlmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pnlkanan.setBackground(new java.awt.Color(0, 0, 153));

        lblpenilaian.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        lblpenilaian.setForeground(new java.awt.Color(255, 255, 255));
        lblpenilaian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posttest3/gambar/penilaian.png"))); // NOI18N
        lblpenilaian.setText("PENILAIAN");

        lblpengunjung.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        lblpengunjung.setForeground(new java.awt.Color(255, 255, 255));
        lblpengunjung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posttest3/gambar/pengunjung.jpg"))); // NOI18N
        lblpengunjung.setText("PENGUNJUNG");

        javax.swing.GroupLayout pnlkananLayout = new javax.swing.GroupLayout(pnlkanan);
        pnlkanan.setLayout(pnlkananLayout);
        pnlkananLayout.setHorizontalGroup(
            pnlkananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlkananLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pnlkananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblpengunjung)
                    .addComponent(lblpenilaian))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlkananLayout.setVerticalGroup(
            pnlkananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlkananLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblpenilaian)
                .addGap(30, 30, 30)
                .addComponent(lblpengunjung)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        pnlbawah.setBackground(new java.awt.Color(51, 51, 255));

        lblcopy.setForeground(new java.awt.Color(255, 255, 255));
        lblcopy.setText("Copyright@2017");

        javax.swing.GroupLayout pnlbawahLayout = new javax.swing.GroupLayout(pnlbawah);
        pnlbawah.setLayout(pnlbawahLayout);
        pnlbawahLayout.setHorizontalGroup(
            pnlbawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlbawahLayout.createSequentialGroup()
                .addGap(562, 562, 562)
                .addComponent(lblcopy)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlbawahLayout.setVerticalGroup(
            pnlbawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlbawahLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(lblcopy)
                .addGap(34, 34, 34))
        );

        pnlhome.setBackground(new java.awt.Color(153, 153, 255));
        pnlhome.setLayout(new java.awt.CardLayout());

        lblhh.setText("Ini Adalah Halaman Utama");
        pnlhome.add(lblhh, "card2");

        pnlabout.setBackground(new java.awt.Color(153, 153, 255));
        pnlabout.setLayout(new java.awt.CardLayout());

        lblha.setText("Ini Adalah Halaman Tentang UnMul");
        pnlabout.add(lblha, "card2");

        pnlcu.setBackground(new java.awt.Color(153, 153, 255));
        pnlcu.setLayout(new java.awt.CardLayout());

        lblhcu.setText("Narahubung");
        pnlcu.add(lblhcu, "card2");

        javax.swing.GroupLayout pnltengahLayout = new javax.swing.GroupLayout(pnltengah);
        pnltengah.setLayout(pnltengahLayout);
        pnltengahLayout.setHorizontalGroup(
            pnltengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnltengahLayout.createSequentialGroup()
                .addGroup(pnltengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlbawah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlatas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnltengahLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblkiri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnltengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnltengahLayout.createSequentialGroup()
                                .addGap(263, 263, 263)
                                .addComponent(lblstart, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnltengahLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(pnlhome, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnlabout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(pnlcu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(181, 181, 181)))
                        .addComponent(pnlkanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1565, 1565, 1565))
        );
        pnltengahLayout.setVerticalGroup(
            pnltengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnltengahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlatas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnltengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlkanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblkiri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnltengahLayout.createSequentialGroup()
                        .addGroup(pnltengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnltengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(pnlabout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pnlcu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlhome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addComponent(lblstart, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlbawah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(782, Short.MAX_VALUE))
        );

        getContentPane().add(pnltengah, java.awt.BorderLayout.CENTER);

        submenuutama.setText("DATA");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Program Studi");
        submenuutama.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("Akreditasi");
        jCheckBoxMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem3ActionPerformed(evt);
            }
        });
        submenuutama.add(jCheckBoxMenuItem3);

        menuutama.add(submenuutama);

        submenuedit.setText("EDIT");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Admin");
        submenuedit.add(jCheckBoxMenuItem1);

        menuutama.add(submenuedit);

        menukeluar.setText("KELUAR");
        menukeluar.setActionCommand("");
        menukeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menukeluarActionPerformed(evt);
            }
        });
        menuutama.add(menukeluar);

        setJMenuBar(menuutama);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMenuItem3ActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        // TODO add your handling code here:
        pnlhome.setVisible(true);
        pnlabout.setVisible(false);
        pnlcu.setVisible(false);
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btnaboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaboutActionPerformed
        // TODO add your handling code here:
        pnlhome.setVisible(false);
        pnlabout.setVisible(true);
        pnlcu.setVisible(false);
    }//GEN-LAST:event_btnaboutActionPerformed

    private void btncuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncuActionPerformed
        // TODO add your handling code here:
        pnlhome.setVisible(false);
        pnlabout.setVisible(false);
        pnlcu.setVisible(true);
    }//GEN-LAST:event_btncuActionPerformed

    private void menukeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menukeluarActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_menukeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sispk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sispk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sispk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sispk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sispk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnabout;
    private javax.swing.JButton btncu;
    private javax.swing.JButton btnhome;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JLabel lblcopy;
    private javax.swing.JLabel lblfikti;
    private javax.swing.JLabel lblfkti;
    private javax.swing.JLabel lblgallery;
    private javax.swing.JLabel lblha;
    private javax.swing.JLabel lblhcu;
    private javax.swing.JLabel lblhh;
    private javax.swing.JLabel lblhistory;
    private javax.swing.JPanel lblkiri;
    private javax.swing.JLabel lbllogin;
    private javax.swing.JLabel lblpengunjung;
    private javax.swing.JLabel lblpenilaian;
    private javax.swing.JLabel lblpps;
    private javax.swing.JLabel lblspk;
    private javax.swing.JLabel lblstart;
    private javax.swing.JLabel lblum;
    private javax.swing.JLabel lblunmul;
    private javax.swing.JMenu menukeluar;
    private javax.swing.JMenuBar menuutama;
    private javax.swing.JPanel pnlabout;
    private javax.swing.JPanel pnlatas;
    private javax.swing.JPanel pnlbawah;
    private javax.swing.JPanel pnlcu;
    private javax.swing.JPanel pnlhome;
    private javax.swing.JPanel pnlkanan;
    private javax.swing.JPanel pnlmenu;
    private javax.swing.JPanel pnltengah;
    private javax.swing.JMenu submenuedit;
    private javax.swing.JMenu submenuutama;
    // End of variables declaration//GEN-END:variables
}
